export const types = {
    LOGIN_EXITOSO: 'LOGIN_EXITOSO',
    LOGIN_ERROR: 'LOGIN_ERROR',
    CERRAR_SESION: 'CERRAR_SESION',
    RESET__ERROR: 'RESET__ERROR',
    OBTENER_USUARIO: 'OBTENER_USUARIO',
    /*REGISTRAR COLABORADOR*/
    REGISTRO_EXITOSO: 'REGISTRO_EXITOSO',
    REGISTRO_ERROR: 'REGISTRO_ERROR',
    /*LISTAR COLABORADOR*/
    OBTENER_COLABORADORES: 'OBTENER_COLABORADORES',
    OBTENER_ERROR: 'OBTENER_ERROR',
    RESETEAR_ERROR_REGISTRO: 'RESETEAR_ERROR_REGISTRO',
    RESET_LOADING: 'RESET_LOADING',
    COLABORADOR_ACTUAL: 'COLABORADOR_ACTUAL',
    COLABORADOR_ACTUAL_RESET: 'COLABORADOR_ACTUAL_RESET',
    ACTUALIZAR_INPUT: 'ACTUALIZAR_INPUT',
    ACTUALIZAR_COLABORADOR: 'ACTUALIZAR_COLABORADOR',
    /* Eliminar */
    ELIMINAR_COLABORADOR: 'ELIMINAR_COLABORADOR',

    /* Producto */
    REGISTRO_EXITOSO_PRODUCTO: 'REGISTRO_EXITOSO_PRODUCTO',
    REGISTRO_ERROR_PRODUCTO: 'REGISTRO_ERROR_PRODUCTO',
    /*LISTAR COLABORADOR*/
    OBTENER_COLABORADORES_PRODUCTO: 'OBTENER_COLABORADORES_PRODUCTO',
    OBTENER_ERROR_PRODUCTO: 'OBTENER_ERROR_PRODUCTO',
    RESETEAR_ERROR_REGISTRO_PRODUCTO: 'RESETEAR_ERROR_REGISTRO_PRODUCTO',
    RESET_LOADING_PRODUCTO: 'RESET_LOADING_PRODUCTO',
    COLABORADOR_ACTUAL_PRODUCTO: 'COLABORADOR_ACTUAL_PRODUCTO',
    COLABORADOR_ACTUAL_RESET_PRODUCTO: 'COLABORADOR_ACTUAL_RESET_PRODUCTO',
    ACTUALIZAR_INPUT_PRODUCTO: 'ACTUALIZAR_INPUT_PRODUCTO',
    ACTUALIZAR_COLABORADOR_PRODUCTO: 'ACTUALIZAR_COLABORADOR_PRODUCTO',
    /* Eliminar */
    ELIMINAR_COLABORADOR_PRODUCTO: 'ELIMINAR_COLABORADOR_PRODUCTO',
}