export const types = {
    LOGIN_EXITOSO: 'LOGIN_EXITOSO',
    LOGIN_ERROR: 'LOGIN_ERROR',
    CERRAR_SESION: 'CERRAR_SESION',
    RESET__ERROR: 'RESET__ERROR',
    OBTENER_USUARIO: 'OBTENER_USUARIO',
}